--PERMISSÃO
GRANT 
--OBJETO
ON
--USUARIO OU ROLE
TO
--TERCEIRIZAR PERMISSÕES DE UM USUÁRIO NÃO ADMIN PARA OUTROS
[WITH GRANT OPTION];

--PARA CRIA UM USUARIO
CREATE USER nome_usuario WITH PASSWORD 'senha';

--EXEMPLO
CREATE USER Wesley WITH PASSWORD '1234';
--GRUPOS DE USUARIO QUE FACILITAM O GERENCIAMENTO DE PERMISSÃO
CREATE ROLE developer;
--COLOCA O USUARIO DENTRO DO AGRUPAMENTO
GRANT developer TO Wesley;

CREATE USER Nissin WITH PASSWORD '4567';

GRANT developer TO Nissin;

--FORNRCER PERMISSÕES AOS USUARIOS
GRANT SELECT ON hospedes TO Wesley;
--PERMITE QUE UM USUARIO QUE RECEBEU UMA PERMISSÃO REPASSE A OERMISSÃO PARA OUTRO USUARIO, PODENDO CEDER MULTIPLAS PERMISSÕES
GRANT SELECT
ON hospedes
TO Nissin
WITH GRANT OPTION;

GRANT UPDATE,INSERT
ON hospedes
TO Wesley;
--FORNECE TODOS OS PRIVILEGIOS 
GRANT ALL
ON hospedes
TO Nissin
WITH GRANT OPTION;
--VERIFICA AS PERMISSÕES DOS USUARIOS
SELECT rolname,rolsuper,rolcreaterole,rolcreatedb
FROM pg_roles;
--QUAL USUARIO ESTA LOGADO
SELECT current_user;
--QUAL USUARIO INICIOU O SISTEMA
SELECT session_user;
--SAI DO PSQL
\q
psql-U postgres -d hotel

--USUÁRIO QUE INICIOU A SESSÃO
SELECT SESSION_USER;

--USUÁRIO QUE ESTA NO CAMANDO DA SESSÃO
SELECT CURRENT_USER;

--MUDAR USUÁRIO SEM SAIR DA SESSÃO
SET ROLE Wesley;

--LISTAR USUÁRIOS
\du 

--CONECTAR UM USUAÁRIO INICIANDOM UMA NOVA SESSÃO
\c nome_da_base nome_usuário

--ALTERAR POSSE DE UMA TABELA PARA OUTRO USUÁTIO
ALTER TABLE tabela OWNER TO novo_usuário;

GRANT SELECT
ON hospedes
TO aluno1;

GRANT SELECT
ON hospedes, quartos, reservas, servicos, consumos
TO aluno1;

GRANT INSERT
ON hospedes, quartos, reservas, servicos, consumos
TO aluno2;

\c hotel aluno2;


INSERT INTO servicos(descricao,valor)
VALUES('jujuba',15);

REVOKE SELECT
ON hospedes, quartos, reservas, servicos, consumos
FROM aluno1;

REVOKE GRANT OPTION FOR permissão
ON objeto
FROM usuário_ou_role[];

GRANT UPDATE 
ON consumos
TO aluno2