--vai selecionar para consulta os valores na tabela quarto e em valor diaria colcoar um apelido, no caso não muda nada pois é o memso nome
SELECT NUMERO, TIPO, VALOR_DIARIA 
AS "valor diaria", 
STATUS FROM QUARTOS;

--SELECIONA OS VALORES A SEREM USADOS E FAZ A MULTIPLICAÇÃO E ARMAZENA EM UMA NOVA TABELA TEMPORÁRIA
SELECT NUMERO,TIPO, VALOR_DIARIA, VALOR_DIARIA*7 FROM QUARTOS;

--TABELA TEMPORÁRIA AGORA COM UM NOME
SELECT NUMERO,TIPO, VALOR_DIARIA, VALOR_DIARIA*7 AS "VALOR SEMANAL"FROM QUARTOS;

-- VAI MULTIPLICAR O VALOR DA DIARIA, E RESULTAR EM VALOR SEMANAL E M SEGUINDA VAI DA UM DESCONTO DE 10% E ARMAZENAR NA TABELA NOMEADA 
--NO SEGUNDO FAZER O EMSMO SO QUE COM O VALOR QUE FOI DESONTADO
-- AS ASPAS NO "APELIDO" SE COLOCAR PARA USAR ESPAÇOS ENTRE O NOME SEM PRECISAR DO (_)
SELECT NUMERO,TIPO, VALOR_DIARIA, VALOR_DIARIA*7*0.9 AS "VALOR SEMANAL COM 10%", VALOR_DIARIA*7*0.1 AS DESCONTO FROM QUARTOS;

--CONSULTAR STATUS DOS QUARTOS LIVRES
SELECT * FROM QUARTOS WHERE STATUS = 'Livre';

----CONSULTAR STATUS DOS QUARTOS OCUPADOS 
--O ILIKE SERVE PARA NÃO DIFERECIAR O NOME MAIUSCULO OU MINUSCULO
SELECT * FROM QUARTOS WHERE STATUS ILIKE 'ocupado';

----CONSULTAR STATUS DOS QUARTOS OCUPADOS 
--O LIKE SERVE PARA DOFERECIAR O NOME MAIUSCULO DO MINUSCULO
SELECT * FROM QUARTOS WHERE STATUS LIKE 'Ocupado';

--CONSULTAR OS SEGUINTES INDICES EM HOSPEDES COM O NOME SILVA INCLUSO, NO COMEÇO NO FIM OU NO MEIO DO NOME.
SELECT DISTINCT NOME,DATA_NASCIMENTO FROM HOSPEDES WHERE NOME ILIKE '%SILVA%';

-- CONSULTA OS INDEICES QUE ESTÃO ENTRE AS DATAS MARCADAS
SELECT NOME,DATA_NASCIMENTO FROM HOSPEDES
WHERE DATA_NASCIMENTO >= '1970-01-01' AND DATA_NASCIMENTO < '1979-12-31';

--CONSULTA QUARTOS QUE ESTÃO ENTRE OS SEGUINTES VALORES DIARIOS
SELECT*FROM QUARTOS
WHERE VALOR_DIARIA BETWEEN 200 AND 500;