NOT (status = 'Ocupado')

status <> 'Ocupado'

SELECT NOME,DATA_NASCIMENTO FROM HOSPEDES 
WHERE NOT (DATA_NASCIMENTO BETWEEN '1980-01-01' AND '1989-12-31');

SELECT NOME,DATA_NASCIMENTO FROM HOSPEDES 
WHERE DATA_NASCIMENTO NOT BETWEEN '1980-01-01' AND '1989-12-31';

--SELECIONA HOSPEDES QUEM NÃO TEM NUMERO DE TELEFONE INSERIDO
SELECT*FROM hospedes
WHERE telefone IS NULL;

SELECT*FROM hospedes
WHERE email IS NOT NULL;

SELECT*FROM quartos
WHERE (tipo= 'Suíte' OR tipo = 'Luxo')
AND valor_diaria > 300
AND status = 'Livre';

--RETORNA O VALOR FINAL DA TABELA SEM OS SEUS COMPONENTES
SELECT COUNT (*) FROM RESERVAS;

SELECT COUNT (*) AS "TOTAL DE RESERVAS"
FROM RESERVAS;

SELECT COUNT (*) AS "TOTAL DE RESERVAS"
FROM QUARTOS;

SELECT COUNT (*) AS "TOTAL DE RESERVAS"
FROM SERVICOS;

SELECT COUNT (*) AS "TOTAL DE RESERVAS"
FROM CONSUMOS;

SELECT SUM(valor_total) 
FROM RESERVAS
WHERE NUMERO_QUARTO = 09;

SELECT SUM(valor_total) 
FROM RESERVAS
WHERE (DATA_ENTRADA BETWEEN '2023=01-01' AND '2023=06-30');

SELECT AVG(valor_diaria) AS MEDIA_DIARIA
FROM QUARTOS
WHERE TIPO = 'Luxo';

SELECT MIN(valor_diaria) AS diaria_minima, MAX(valor_diaria) AS diaria_maxima, AVG(valor_diaria) AS MEDIA_DIARIA
FROM QUARTOS;

SELECT COUNT(*) AS total_reservas,
SUM(valor_total) AS soma_reservas,
AVG(valor_total) AS media_reservas
FROM RESERVAS;

SELECT ROUND(AVG(valor_diaria),2) AS media_diaria
FROM quartos;

SELECT TO_CHAR(SUM(valor_total),'999G999D00') AS media_diaria
FROM RESERVAS;

SELECT DATA_ENTRADA, TO_CHAR(DATA_ENTRADA,'DD/MM/YYYY') AS DATA_FORMATADA
FROM RESERVAS;